# -*- coding: utf-8 -*-
#!/home/abhi/anaconda3/envs/dev1/bin/python

# Import the graphics and plotting libraries for output visulization
import matplotlib.pyplot as plt

"""Module to process the output generated by the HMM agent during testing."""

# Post-processing module
class PostProcessor:
  
  plt.style.use('seaborn-darkgrid')
  
  # Plot the most basic plot with scores on the y-axis and sequence index
  # on the x-axis ( need to be improved to include timestamps, sensors, etc.)
  def plot_basic(score_list, sequence_length):
    
    plt.title('Log probability scores for event sequences of length %d' %(sequence_length))
    plt.ylabel('Log probability score')
    plt.xlabel('Event sequence index')
    
    plt.plot(score_list)
    plt.show()
